Vagrant.configure("2") do |config|
	config.vm.box = 'VistaIE7'
	config.vm.box_url = 'http://aka.ms/vagrant-vista-ie7'
	config.vm.guest = :windows
	config.vm.boot_timeout = 1
	config.vm.communicator = "winrm"
	config.vm.provider "virtualbox" do |vm|
	  vm.gui = true
	end
end
