Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    web.vm.box = "morawskim/openSUSE-42.2-x86_64"
    #web.vm.box = "opensuse/openSUSE-13.2-x86_64"
    web.vm.network "private_network", ip: "192.168.50.5"

    web.vm.provision :shell, :inline => <<-EOS
zypper --non-interactive in !exim postfix mailx

tee /etc/postfix/main.cf << "EOF"
myhostname = box1.mydomain.com
mydomain = mydomain.com
myorigin = $mydomain
inet_interfaces = loopback-only
mydestination =
relayhost = 192.168.50.4
inet_protocols = ipv4

# set defaults for opensuse
setgid_group = maildrop
queue_directory = /var/spool/postfix
daemon_directory = /usr/lib/postfix
data_directory = /var/lib/postfix
EOF

systemctl restart postfix.service
systemctl enable postfix.service
    EOS
  end

  config.vm.define "db" do |db|
    db.vm.box = "morawskim/openSUSE-42.2-x86_64"
    #db.vm.box = "opensuse/openSUSE-13.2-x86_64"
    db.vm.network "private_network", ip: "192.168.50.4"
    db.vm.provision :shell, :inline => <<-EOS
zypper --non-interactive in !exim postfix mailx

tee /etc/postfix/main.cf << "EOF"
myhostname = mail.mydomain.com
mydomain = mydomain.com
myorigin = $mydomain
inet_interfaces = all
mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain
mynetworks = 192.168.0.0/24, 127.0.0.0/8, 192.168.50.0/24
inet_protocols = ipv4

# set defaults for opensuse
setgid_group = maildrop
queue_directory = /var/spool/postfix
daemon_directory = /usr/lib/postfix
data_directory = /var/lib/postfix
EOF

systemctl restart postfix.service
systemctl enable postfix.service

useradd user1
useradd user2

sysconf_addword /etc/sysconfig/SuSEfirewall2 FW_CONFIGURATIONS_EXT smtp
    EOS
  end
end
