Vagrant.configure("2") do |config|
	config.vm.box = 'XPIE8'
	config.vm.box_url = "http://aka.ms/vagrant-xp-ie8"
	config.vm.guest = :windows
	config.vm.boot_timeout = 1
	config.vm.communicator = "winrm"
	config.vm.provider "virtualbox" do |vm|
	      vm.gui = true
	end
end
